<a href="https://colab.research.google.com/github/SangjunRyu/ai-security/blob/master/5thweek/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
a=100
print(a)

100


In [4]:
b = "this is string type"
print(b)

this is string type


In [5]:
b="a"
print(b)

a


In [9]:

sum = 0
for i in range(10):
    sum += i
print(sum)

45


In [12]:
def HowtoGo(money):
  if money > 5000:
     print("택시타")
  elif money > 1250:
     print("대중교통")
  else:
     print("걸어가")
 
HowtoGo(1000)
HowtoGo(2500)
HowtoGo(10000)

걸어가
대중교통
택시타


In [0]:
import torch

In [14]:
x = torch.empty(5,3)
print(x)

tensor([[2.9871e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.4775e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 7.7781e+31]])


In [15]:
x = torch.rand(5,3)
print(x)

tensor([[0.5747, 0.3028, 0.8911],
        [0.8941, 0.7379, 0.7067],
        [0.5975, 0.7969, 0.7785],
        [0.8342, 0.6947, 0.9114],
        [0.5358, 0.3298, 0.1152]])


In [17]:
y= torch.rand(5,3)
print(y)
print(torch.add(x,y))

tensor([[0.6486, 0.7394, 0.2906],
        [0.2418, 0.5582, 0.4929],
        [0.7850, 0.4550, 0.8553],
        [0.9190, 0.1500, 0.4009],
        [0.4622, 0.9104, 0.6719]])
tensor([[1.2233, 1.0422, 1.1816],
        [1.1358, 1.2961, 1.1996],
        [1.3825, 1.2519, 1.6338],
        [1.7532, 0.8446, 1.3124],
        [0.9980, 1.2402, 0.7871]])
